
# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction. 

The prerequisites for understanding and setting up at RRT survey are basic knowledge of surveys and statistics. It is also necessary to have R installed with packages like RRT. 

For the data that this method is used on missing values should be avoided. The data should also fit the expected ranges. Whether that is for numerical or categorical questions. The data distribution is not as important for RRT, but when analyzing the data it may be more important to look into. 


Basic Components of RRT:
1. Design a survey that includes sensitive questions
2. Set up the randomization. For examples, coin flips
3. Collect the responses
4. Analyze the randomized data

The user should ask if the randomization setup is clear and if the questions are appropriate for RRT.
